### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Aadriya** [JotaSe/advanced-react-redux-examples#1]
When I change This App TO SSR Shows The Error

Invariant Violation: Could not find "store" in either the context or props of "Connect(App)". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(App)".
   at invariant (/home/megha/public_html/universal-react-example/node_modules/invariant/invariant.js:42:15)
   at new Connect (/home/megha/public_html/universal-react-example/node_modules/react-redux/lib/components/connectAdvanced.js:134:33)
   at /home/megha/public_html/universal-react-example/node_modules/react-dom/lib/ReactCompositeComponent.js:295:18
   at measureLifeCyclePerf (/home/megha/public_html/universal-react-example/node_modules/react-dom/lib/ReactCompositeComponent.js:75:12)
   at null.ReactCompositeComponent._constructComponentWithoutOwner (/home/megha/public_html/universal-react-example/node_modules/react-dom/lib/ReactCompositeComponent.js:294:16)
   at null.ReactCompositeComponent._constructComponent (/home/megha/public_html/universal-react-example/node_modules/react-dom/lib/ReactCompositeComponent.js:280:21)
   at null.ReactCompositeComponent.mountComponent (/home/megha/public_html/universal-react-example/node_modules/react-dom/lib/ReactCompositeComponent.js:188:21)
   at Object.ReactReconciler.mountComponent (/home/megha/public_html/universal-react-example/node_modules/react-dom/lib/ReactReconciler.js:46:35)
   at null.ReactCompositeComponent.performInitialMount (/home/megha/public_html/universal-react-example/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
   at null.ReactCompositeComponent.mountComponent (/home/megha/public_html/universal-react-example/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)

**Comment by JotaSe** [comment]
Hi, could you provide more details?

**Comment by Aadriya** [comment]
ok My componets and Router, Server pages are
![screenshot from 2017-04-13 08-53-43](https://cloud.githubusercontent.com/assets/26130750/24989005/0e641b10-2027-11e7-90a7-6cf513638226.png)
![screenshot from 2017-04-13 08-53-58](https://cloud.githubusercontent.com/assets/26130750/24989006/0e671bd0-2027-11e7-818f-c7a53f916e58.png)
![screenshot from 2017-04-13 08-54-33](https://cloud.githubusercontent.com/assets/26130750/24989007/0e67f6ae-2027-11e7-8140-aeda35fbd9a8.png)
![screenshot from 2017-04-13 08-55-22](https://cloud.githubusercontent.com/assets/26130750/24989009/0e692eca-2027-11e7-9c1c-32b2ea0d79f7.png)
![screenshot from 2017-04-13 08-55-29](https://cloud.githubusercontent.com/assets/26130750/24989008/0e691b38-2027-11e7-901a-e45c350b0950.png)
